### ISSUE TITLE
Duplicates shout-python ?

### ISSUE THREAD

**Issue by yomguy** [LeonB/pylibshout#1]
Hi !

Would libpyshout be a fork of shout-python or is it a better shouting bindings for icecast2 and why ?
http://www.icecast.org/download.php

Thanks,
YomGuy

**Comment by LeonB** [comment]
It's not a fork. It's completely new. The API of shout-python and shout-python is almost the same to keep it simple.
I decided to make a module based on libshout of my own because shout-python gave me segmentation faults and py-shout (?) refused to build.

**Comment by yomguy** [comment]
I understand.. 
Surprising because shout-python works very well here on Debian with DeeFuzzer, my own source client ( http://svn.parisson.org/deefuzzer/ )

What is your platform ?
Yomguy

**Comment by LeonB** [comment]
Ubuntu 9.04.

Even with the example that came with shout-python it segfaulted :S
Ah well, the advange of creating my own libshout module is that I know exactly how it works. And beause it's based on Cython it looks more like a regular python class so it's easier to adjust and use.

I've also been thinking about creating an ezstrean/deefuzzer like client. But I don't know what it should exactly do :)
